info = [
    "NeoFinder Python API",
    "=" * 40, "",
    "STANDARD I/O (injected by handler):",
    "  STDIN.text / STDIN.lines       -- piped input (from buffer or chain)",
    "  STDIN.read_buffer()            -- load current buffer into STDIN",
    "  STDIN.varname                  -- variables from handler 'in'",
    "",
    "  STDOUT.print('line')           -- collect output line",
    "  STDOUT.write(['a','b'])        -- collect multiple lines",
    "  STDOUT.text / STDOUT.lines     -- read collected output",
    "  STDOUT.clear()                 -- reset",
    "  (auto-flushed to output buffer after execution)",
    "",
    "  STDERR.print('error msg')      -- collect error",
    "  STDERR.write(['a','b'])        -- collect multiple errors",
    "  STDERR.has_errors()            -- check if errors exist",
    "  (auto-shown to user after execution)",
    "",
    "HANDLER .json:",
    '  "in":   {"var": "prompt"}   -- ask user, inject as var + STDIN',
    '  "out":  "[Title ${var}]"    -- output buffer title',
    '  "pipe": "buffer"            -- load current buffer into STDIN',
    '  "deps":  ["input","output"] -- declares dependencies',
    "",
    "CONTEXT:        nf.file  nf.dir  nf.line  nf.filetype  nf.theme",
    "",
    "BUFFER:         nf.buf.lines  nf.buf.text  nf.buf.name",
    "  read:         nf.buf.line  nf.buf[0]  nf.buf.selection",
    "  write:        nf.buf.write(x)  nf.buf.append(x)  nf.buf.clear()",
    "",
    "OUTPUT:         nf.out.write(lines, title)  nf.out.append(x)",
    "                nf.out.clear()  nf.out.close()",
    "",
    "SHELL:          stdout, stderr, rc = nf.sh(cmd)",
    "                nf.sh_output(cmd)   -> output buffer",
    "                nf.sh_lines(cmd)    -> list of lines",
    "",
    "INPUT:          nf.input(prompt)  nf.confirm(msg)  nf.select(items)",
    "",
    "TAGS:           nf.tags.groups()  nf.tags.files(group)",
    "                nf.tags.add(path, group)  nf.tags.remove(path)",
    "",
    "FILES:          nf.open(p)  nf.vsplit(p)  nf.split(p)",
    "                nf.scratch(lines, title)  nf.buffers()",
    "",
    "MESSAGES:       nf.echo(x)  nf.warn(x)  nf.error(x)",
]

STDOUT.write(info)
